In [1]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [7]:
matrix=np.array([[1,2,3,8],[6,7,4,2]])
print(matrix)

[[1 2 3 8]
 [6 7 4 2]]


In [16]:
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)

(2, 4)
2
8
int64


In [17]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.sum(a))
print(np.mean(a))
print(np.std(a))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32
32
6
2.0
0.816496580927726
