In [3]:
import numpy as np # type: ignore
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [6]:
import numpy as np # type: ignore

# Create a 0D array
arr_0d = np.array(42)
print("0D Array:")
print(arr_0d)

# Create a 1D array
arr_1d = np.array([6, 7, 8, 9, 10])
print("1D Array:")
print(arr_1d)

# Create a 2D array
arr_2d = np.array([[11, 12, 13],[14, 15, 16]])
print("2D Array:")
print(arr_2d)

0D Array:
42
1D Array:
[ 6  7  8  9 10]
2D Array:
[[11 12 13]
 [14 15 16]]
