In [7]:
import numpy as np # type: ignore
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [ ]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

# Create a 2D array
arr_2d = np.array([[6, 7, 8], [9, 10, 11]])
print("2D Array:")
print(arr_2d)

# Accessing array elements
print("Accessing array elements:")
print("First element of arr_1d:", arr_1d[0])
print("Element at row 0, column 1 of arr_2d:", arr_2d[0, 1])

# Array operations
print("Array operations:")
print("Sum of arr_1d:", np.sum(arr_1d))
print("Mean of arr_2d:", np.mean(arr_2d))
print("Max of arr_1d:", np.max(arr_1d))
print("Min of arr_2d:", np.min(arr_2d))

# Reshaping arrays
print("Reshaping arrays:")
reshaped_arr_1d = arr_1d.reshape((5, 1))
print("Reshaped arr_1d:")
print(reshaped_arr_1d)

In [8]:
import numpy as np # type: ignore

# Create a 0D array
arr_0d = np.array(42)
print("0D Array:")
print(arr_0d)

# Create a 1D array
arr_1d = np.array([6, 7, 8, 9, 10])
print("1D Array:")
print(arr_1d)

# Create a 2D array
arr_2d = np.array([[11, 12, 13],[14, 15, 16]])
print("2D Array:")
print(arr_2d)

# Create a 3D array
arr_3d = np.array([[11, 12, 13],[14, 15, 16],[17, 18, 19]])
print("3D Array:")
print(arr_3d)

# Create a 4D array
arr_4d = np.array([[11, 12, 13],[14, 15, 16],[17, 18, 19],[20, 21, 22]])
print("4D Array:")
print(arr_4d)

# Create a 5D array
arr_5d = np.array([[11, 12, 13],[14, 15, 16],[17, 18, 19],[20, 21, 22],[23, 24, 25]])
print("5D Array:")
print(arr_5d)

0D Array:
42
1D Array:
[ 6  7  8  9 10]
2D Array:
[[11 12 13]
 [14 15 16]]
3D Array:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
4D Array:
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
5D Array:
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]
 [23 24 25]]
