In [7]:
import numpy as np # type: ignore
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [8]:
import numpy as np # type: ignore

# Create a 0D array
arr_0d = np.array(42)
print("0D Array:")
print(arr_0d)

# Create a 1D array
arr_1d = np.array([6, 7, 8, 9, 10])
print("1D Array:")
print(arr_1d)

# Create a 2D array
arr_2d = np.array([[11, 12, 13],[14, 15, 16]])
print("2D Array:")
print(arr_2d)

# Create a 3D array
arr_3d = np.array([[11, 12, 13],[14, 15, 16],[17, 18, 19]])
print("3D Array:")
print(arr_3d)

# Create a 4D array
arr_4d = np.array([[11, 12, 13],[14, 15, 16],[17, 18, 19],[20, 21, 22]])
print("4D Array:")
print(arr_4d)

# Create a 5D array
arr_5d = np.array([[11, 12, 13],[14, 15, 16],[17, 18, 19],[20, 21, 22],[23, 24, 25]])
print("5D Array:")
print(arr_5d)

0D Array:
42
1D Array:
[ 6  7  8  9 10]
2D Array:
[[11 12 13]
 [14 15 16]]
3D Array:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
4D Array:
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
5D Array:
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]
 [23 24 25]]
